POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "willy23",
    "name": "Willy",
    "password": "4321"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdyb2JlcnQiLCJpZCI6IjY0OWZmZTBhNDAwOGY1YWFiODkwNTU1MSIsImlhdCI6MTY4ODIyMTQ1MiwiZXhwIjoxNjg4MjI1MDUyfQ.RNxFtN0SVzqS8cVTcLtFFGCO8jrSyo-4J_2T9XXnQBw

{
    "title": "Prueba233a",
    "author": "Floppa",
    "likes": 3,
    "url": "http://google.com"
}
###

DELETE http://localhost:3003/api/blogs/64a00bb9d6765bf9eb866e07
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbGx5MjMiLCJpZCI6IjY0OWZmZTkzMWRjMDdlNDcxYzFkZjVhZCIsImlhdCI6MTY4ODIyMjQ4MywiZXhwIjoxNjg4MjI2MDgzfQ.zc4jMc7184sWxMO6liPOaNJ502saSxwgylSH9wI0rO4

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "willy23",
    "password": "1234"
}